### ISSUE TITLE
RSLVD?: Invalid literal during cutoff: " "

### ISSUE THREAD

**Issue by LillianZ** [secastel/phaser#51]
Error:
...
               completed chromosome X...
          processing mapped reads...
          using alignment score cutoff of 122
Traceback (most recent call last):
  File "tools/phaser-v1.1.0/phaser/phaser.py", line 2359, in <module>
    main();
  File "tools/phaser-v1.1.0/phaser/phaser.py", line 170, in main
    parse_sample(sample_name, map_sample_column, args.bam, args.o, contig_ban)
  File "tools/phaser-v1.1.0/phaser/phaser.py", line 262, in parse_sample
    start_time, vcf_out, sample_out_path, last_chr=True, pi_block_value = 0)
  File "tools/phaser-v1.1.0/phaser/phaser.py", line 555, in process_vcf
    pool_output = parallelize(process_mapping_result, result_files);
  File "tools/phaser-v1.1.0/phaser/phaser.py", line 2090, in parallelize
    pool_output.append(function(input));
  File "tools/phaser-v1.1.0/phaser/phaser.py", line 1303, in process_mapping_result
    if use_as_cutoff == False or int(fields[4]) >= as_cutoff:
ValueError: invalid literal for int() with base 10: ''
Command exited with non-zero status 1

**Comment by LillianZ** [comment]
Works without the options; and works on Hapcut both with and without those options

**Comment by secastel** [comment]
Sorry for the delayed response. The reason for this is that one of your BAMs had an alignment score tag (AS), while the other did not. phASER has problems if the alignment score is found in some, but not all alignments in a single bam. The correct way to solve this is what you've done already, which is to provide the BAMs separately. Thanks!
