### ISSUE TITLE
example fails on blacklist intervals

### ISSUE THREAD

**Issue by vjcitn** [secastel/phaser#54]
trying out phaser at NHGRI Computational medicine hackation

is the example at https://stephanecastel.wordpress.com/2017/02/15/how-to-generate-ase-data-with-phaser/ known to work with current code?

##################################################
              Welcome to phASER v1.1.1
  Author: Stephane Castel (scastel@nygenome.org)
  Updated by: Bishwa K. Giri (bkgiri@uncg.edu)
##################################################

Completed the check of dependencies and input files availability... 

STARTED "Read backed phasing and ASE/haplotype analyses" ... 
    DATE, TIME : 2019-06-10, 18:17:09
#1. Loading heterozygous variants into intervals...
Processing sample named NA06986
    using all the chromosomes ...
    removing blacklisted variants and processing VCF...
#1b. Loading haplotypic count blacklist intervals...
Traceback (most recent call last):
  File "REDO/phaser/phaser/phaser.py", line 2358, in <module>
    main();
  File "REDO/phaser/phaser/phaser.py", line 170, in main
    parse_sample(sample_name, map_sample_column, args.bam, args.o, contig_ban)
  File "REDO/phaser/phaser/phaser.py", line 235, in parse_sample
    for line in raw_interval.split("\n"):
TypeError: a bytes-like object is required, not 'str'

**Comment by vjcitn** [comment]
Apparently if python 2.7 is used these issues do not crop up
