### ISSUE TITLE
fails after omitting blacklist arg to allow progress

### ISSUE THREAD

**Issue by vjcitn** [secastel/phaser#55]
after omitting blacklist arguments, phaser ran for a long time but then ...
               completed chromosome 16...
               completed chromosome 17...
               completed chromosome 22...
               completed chromosome 19...
               completed chromosome 6...
          processing mapped reads...
Traceback (most recent call last):
  File "REDO/phaser/phaser/phaser.py", line 2358, in <module>
    main();
  File "REDO/phaser/phaser/phaser.py", line 170, in main
    parse_sample(sample_name, map_sample_column, args.bam, args.o, contig_ban)
  File "REDO/phaser/phaser/phaser.py", line 262, in parse_sample
    start_time, vcf_out, sample_out_path, last_chr=True, pi_block_value = 0)
  File "REDO/phaser/phaser/phaser.py", line 546, in process_vcf
    alignment_scores = map(int,[x for x in subprocess.check_output("set -euo pipefail && "+"cut -f 5 "+" ".join(result_files), shell=True, executable='/bin/bash').split("\n") if x != ""]);
TypeError: a bytes-like object is required, not 'str'

**Comment by vjcitn** [comment]
use python 2.7 to avoid this?
