### ISSUE TITLE
Error in phaser_gene_ae.py

### ISSUE THREAD

**Issue by netwon123** [secastel/phaser#85]
python phaser_gene_ae.py --haplotypic_counts ph_CRR393228.haplotypic_counts.txt --features gene.sort.bed --o zz.txt

##################################################
          Welcome to phASER Gene AE v1.2.0
  Author: Stephane Castel (stephanecastel@gmail.com)
##################################################

#1 Loading features...
#2 Loading haplotype counts...
/public/home/baoqi/SRWHS/jiangxi_tran/bam/bam268/AS_gene/phaser_gene_ae.py:77: DtypeWarning: Columns (0,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df_haplo_counts_master = pandas.read_csv(args.haplotypic_counts, sep="\t", index_col=False);
#3 Processing results...
    BAM: nan
          generating feature level haplotypic counts...
          outputting feature haplotype counts...
    BAM: A00783:48:HL53YDSXX:4:1416:26784:26334,A00783:48:HL53YDSXX:4:2467:16938:13135,A00783:48:HL53YDSXX:4:2139:7148:12555,A00783:48:HL53YDSXX:4:1319:30915:32205,A00783:48:HL53YDSXX:4:2177:30355:9815
          generating feature level haplotypic counts...
Traceback (most recent call last):
  File "/public/home/baoqi/SRWHS/jiangxi_tran/bam/bam268/AS_gene/phaser_gene_ae.py", line 240, in <module>
    main();
  File "/public/home/baoqi/SRWHS/jiangxi_tran/bam/bam268/AS_gene/phaser_gene_ae.py", line 111, in main
    mapped_reads = variant_feature_reads(row,feature);
  File "/public/home/baoqi/SRWHS/jiangxi_tran/bam/bam268/AS_gene/phaser_gene_ae.py", line 204, in variant_feature_reads
    hap_a_reads += str(row['aReads']).split(";")[xvar_index].split(",");
IndexError: list index out of range

Hi developer, 
   I try all the advices mentioned in issues, but it also did not work. Could you give me some advices?

**Comment by zzzzzd0825** [comment]
Hi, did you solve this？ I meet the same error。

**Comment by netwon123** [comment]
> Hi, did you solve this？ I meet the same error。

I forget it, sorry.

**Comment by zzzzzd0825** [comment]
> > 嗨，你解决了这个吗？我遇到了同样的错误。
> 
> 我忘了，抱歉。

Thanks。
